import { useRef, useCallback } from 'react';
import { Node, Edge, nodeColorMap } from '../lib/graphData';
import { motion } from 'framer-motion';
import { X, Download } from 'lucide-react';

interface ShareCardProps {
  path: Node[];
  edges: Edge[];
  scores: { serendipity: number; curiosity: number; synchronicity: number; fortuity: number; materiality: number };
  onClose: () => void;
}

export function ShareCard({ path, edges, scores, onClose }: ShareCardProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const generateImage = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const w = 800;
    const h = 1200;
    canvas.width = w;
    canvas.height = h;

    // Background
    const gradient = ctx.createLinearGradient(0, 0, w, h);
    gradient.addColorStop(0, '#0a0a1a');
    gradient.addColorStop(1, '#050510');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, w, h);

    // Starfield
    for (let i = 0; i < 100; i++) {
      const x = Math.random() * w;
      const y = Math.random() * h;
      const r = Math.random() * 1.5;
      const alpha = Math.random() * 0.3 + 0.1;
      ctx.fillStyle = `rgba(255, 255, 255, ${alpha})`;
      ctx.beginPath();
      ctx.arc(x, y, r, 0, Math.PI * 2);
      ctx.fill();
    }

    // Title
    ctx.fillStyle = '#c9a227';
    ctx.font = 'bold 36px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('CONNECTIONS', w / 2, 80);

    ctx.fillStyle = '#64748b';
    ctx.font = '16px Outfit, sans-serif';
    ctx.fillText(`${path[0].name} → ${path[path.length - 1].name}`, w / 2, 110);

    // Path visualization
    const startY = 180;
    const stepY = 70;

    path.forEach((node, i) => {
      const y = startY + i * stepY;
      const color = nodeColorMap[node.type] || '#94a3b8';

      // Node dot
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.arc(100, y, 8, 0, Math.PI * 2);
      ctx.fill();

      // Glow
      ctx.fillStyle = color + '30';
      ctx.beginPath();
      ctx.arc(100, y, 16, 0, Math.PI * 2);
      ctx.fill();

      // Connecting line
      if (i < path.length - 1) {
        ctx.strokeStyle = '#1e293b';
        ctx.lineWidth = 2;
        ctx.setLineDash([6, 4]);
        ctx.beginPath();
        ctx.moveTo(100, y + 8);
        ctx.lineTo(100, y + stepY - 8);
        ctx.stroke();
        ctx.setLineDash([]);
      }

      // Node text
      ctx.fillStyle = '#e2e8f0';
      ctx.font = 'bold 20px Outfit, sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(node.name, 140, y + 6);

      // Year
      ctx.fillStyle = '#475569';
      ctx.font = '14px "JetBrains Mono", monospace';
      ctx.fillText(
        node.year > 0 ? String(node.year) : `${Math.abs(node.year)} BC`,
        140, y + 24
      );

      // Edge label
      if (i < path.length - 1 && edges[i]) {
        ctx.fillStyle = edges[i].surpriseFactor > 0.6 ? '#8b5cf6' : '#64748b';
        ctx.font = 'italic 13px Outfit, sans-serif';
        ctx.fillText(edges[i].label, 140, y + 44);
      }
    });

    // Score bars
    const scoreY = startY + path.length * stepY + 60;
    const scoreLabels = ['Serendipity', 'Curiosity', 'Synchronicity', 'Fortuity', 'Materiality'];
    const scoreColors = ['#c9a227', '#8b5cf6', '#06b6d4', '#ef4444', '#10b981'];
    const scoreValues = [scores.serendipity, scores.curiosity, scores.synchronicity, scores.fortuity, scores.materiality];

    ctx.fillStyle = '#64748b';
    ctx.font = 'bold 14px Outfit, sans-serif';
    ctx.fillText('Connection Scores', w / 2, scoreY - 20);

    scoreLabels.forEach((label, i) => {
      const y = scoreY + i * 40;
      const val = scoreValues[i];
      const barW = 300;

      ctx.fillStyle = '#64748b';
      ctx.font = '13px Outfit, sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(label, 200, y + 12);

      // Bar background
      ctx.fillStyle = '#1e293b';
      ctx.beginPath();
      ctx.roundRect(320, y, barW, 16, 8);
      ctx.fill();

      // Bar fill
      ctx.fillStyle = scoreColors[i];
      ctx.beginPath();
      ctx.roundRect(320, y, barW * val, 16, 8);
      ctx.fill();

      // Percentage
      ctx.fillStyle = '#94a3b8';
      ctx.font = '12px "JetBrains Mono", monospace';
      ctx.textAlign = 'left';
      ctx.fillText(`${Math.round(val * 100)}%`, 330 + barW * val + 8, y + 12);
    });

    // Footer
    ctx.fillStyle = '#475569';
    ctx.font = '13px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(`${path.length - 1} connections across ${path.length} inventions`, w / 2, h - 60);
    ctx.fillStyle = '#1e293b';
    ctx.fillText('Generated by Connections Creator', w / 2, h - 40);

    // Download
    const link = document.createElement('a');
    link.download = `connections-${path[0].id}-${path[path.length - 1].id}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }, [path, edges, scores]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center bg-[#050510]/90 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-[#0a0a1a] border border-[#1e293b] rounded-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
        onClick={e => e.stopPropagation()}
      >
        <div className="p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-semibold text-[#e2e8f0]">Share Connection</h2>
            <button onClick={onClose} className="text-[#64748b] hover:text-[#e2e8f0] transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="bg-[#050510] border border-[#1e293b] rounded-lg p-6 mb-6">
            <div className="text-center mb-4">
              <span className="text-[#c9a227] font-bold text-lg">CONNECTIONS</span>
              <p className="text-sm text-[#64748b] mt-1">
                {path[0].name} → {path[path.length - 1].name}
              </p>
            </div>

            <div className="flex flex-col gap-2">
              {path.map((node, i) => (
                <div key={node.id} className="flex items-center gap-3">
                  <div
                    className="w-3 h-3 rounded-full flex-shrink-0"
                    style={{ backgroundColor: nodeColorMap[node.type] || '#94a3b8' }}
                  />
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium text-[#e2e8f0]">{node.name}</span>
                      <span className="text-xs text-[#475569]">
                        {node.year > 0 ? node.year : `${Math.abs(node.year)} BC`}
                      </span>
                    </div>
                    {i < path.length - 1 && edges[i] && (
                      <p className="text-xs text-[#64748b] italic mt-0.5">
                        {edges[i].label}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-4 pt-4 border-t border-[#1e293b]">
              <div className="grid grid-cols-5 gap-2 text-center">
                {[
                  { label: 'Serendipity', val: scores.serendipity, color: '#c9a227' },
                  { label: 'Curiosity', val: scores.curiosity, color: '#8b5cf6' },
                  { label: 'Synchronicity', val: scores.synchronicity, color: '#06b6d4' },
                  { label: 'Fortuity', val: scores.fortuity, color: '#ef4444' },
                  { label: 'Materiality', val: scores.materiality, color: '#10b981' },
                ].map(({ label, val, color }) => (
                  <div key={label}>
                    <div className="text-xs text-[#475569] mb-1">{label}</div>
                    <div className="text-sm font-bold" style={{ color }}>
                      {Math.round(val * 100)}%
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <button
            onClick={generateImage}
            className="w-full bg-[#c9a227] text-[#050510] font-semibold py-3 px-6 rounded-lg hover:bg-[#d4b43a] transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download Share Card
          </button>
        </div>
      </motion.div>

      <canvas ref={canvasRef} className="hidden" />
    </motion.div>
  );
}
